SISALM.WebApp/Areas/General/Controllers/MetaDatoController.cs
using Microsoft.AspNetCore.Mvc;
using SISALM.Entidades.Filtros.General;
using SISALM.Entidades.General;
using SISALM.Logicas.Servicios.General;
using SISALM.WebApp.Areas.General.Models;
using SISALM.WebApp.Commons.Filtros;
using System.Net;

namespace SISALM.WebApp.Areas.General.Controllers
{
    [ModuloGeneralFiltro]
    public class MetaDatoController : Controller
    {
        private readonly IMetaDatoServicio _metaDatoServicio;

        public MetaDatoController(IMetaDatoServicio metaDatoServicio)
        {
            _metaDatoServicio = metaDatoServicio;
        }

        #region Acciones

        public IActionResult Index() => View();

        public IActionResult Nuevo(string callBack = "SetNuevo")
        {
            MetaDato model = new() { Activo = true };
            ViewBag.CallBack = callBack;
            return PartialView("_Nuevo", model);
        }

        [HttpPost]
        public async Task<IActionResult> Nuevo(MetaDatoModel.Nuevo model)
        {
            try
            {
                Validar(model);
                if (ModelState.IsValid)
                {
                    MetaDato entidad = model.Get();
                    await _metaDatoServicio.GuardarAsync(entidad);
                    return Ok(new
                    {
                        entidad.Id
                    });
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        public async Task<IActionResult> Editar(int id, string callBack = "SetEditar")
        {
            try
            {
                MetaDato? model = await _metaDatoServicio.BuscarPorIdAsync(id);
                if (model == null) throw new Exception("No existe el metadato.");
                ViewBag.CallBack = callBack;
                return PartialView("_Editar", model);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Editar(MetaDatoModel.Editar model)
        {
            try
            {
                Validar(model);
                if (ModelState.IsValid)
                {
                    MetaDato entidad = model.Get();
                    await _metaDatoServicio.ActualizarAsync(entidad);
                    return Ok(new
                    {
                        entidad.Id
                    });
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Error");
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        public async Task<IActionResult> Listar(MetaDatoFiltro filtro, int pageIndex, int pageSize)
        {
            try
            {
                List<MetaDato> lista = await _metaDatoServicio.ListarPorPaginaAsync(filtro, pageIndex, pageSize);
                int totalRows = await _metaDatoServicio.ContarAsync(filtro);
                return Ok(new
                {
                    totalRows,
                    lista = lista.Select(x => new
                    {
                        x.Id,
                        x.Codigo,
                        x.Nombre,
                        x.Activo,
                        x.Tipo,
                    })
                });
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        #endregion

        #region Metodos

        [NonAction]
        void Validar(MetaDatoModel.Nuevo entidad)
        {
            ModelState.Clear();
            if (!entidad.Tipo.HasValue) ModelState.AddModelError("Tipo", "Es necesario seleccionar un tipo.");
            if (string.IsNullOrEmpty(entidad.Nombre)) ModelState.AddModelError("Nombre", "Es necesario ingresar el nombre.");
        }

        [NonAction]
        void Validar(MetaDatoModel.Editar entidad)
        {
            ModelState.Clear();
            if (!entidad.Id.HasValue) ModelState.AddModelError("Id", "Es necesario tener un identificador.");
            if (string.IsNullOrEmpty(entidad.Nombre)) ModelState.AddModelError("Nombre", "Es necesario ingresar el nombre.");
        }

        #endregion
    }
}

SISALM.WebApp/Areas/Logistica/Controllers/AlmacenMaterialController.cs
using Microsoft.AspNetCore.Mvc;
using SISALM.Entidades.Filtros.Logistica;
using SISALM.Entidades.General;
using SISALM.Entidades.Logistica;
using SISALM.Logicas.Servicios.General;
using SISALM.Logicas.Servicios.Logistica;
using SISALM.WebApp.Commons.Filtros;
using System.Net;

namespace SISALM.WebApp.Areas.Logistica.Controllers
{
    [ModuloLogisticaFiltro]
    public class AlmacenMaterialController : Controller
    {
        private readonly IAlmacenMaterialServicio _almacenMaterialServicio;
        private readonly IMetaDatoServicio _metaDatoServicio;

        public AlmacenMaterialController(IAlmacenMaterialServicio almacenMaterialServicio, IMetaDatoServicio metaDatoServicio)
        {
            _almacenMaterialServicio = almacenMaterialServicio;
            _metaDatoServicio = metaDatoServicio;
        }

        public async Task<IActionResult> Index()
        {
            List<MetaDato> unidadMedidas = await _metaDatoServicio.ListarAsync(new Entidades.Filtros.General.MetaDatoFiltro { Tipo = Entidades.Constantes.TipoMetaDato.UNIDAD_MEDIDA });
            ViewBag.UnidadMedidas = unidadMedidas;
            return View();
        }

        public async Task<IActionResult> Listar(AlmacenMaterialFiltro filtro, int pageIndex, int pageSize)
        {
            try
            {
                List<AlmacenMaterial> lista = await _almacenMaterialServicio.ListarPorPaginaAsync(filtro, pageIndex, pageSize);
                int totalRows = await _almacenMaterialServicio.ContarAsync(filtro);
                return Ok(new
                {
                    totalRows,
                    lista = lista.Select(x => new
                    {
                        x.Id,
                        x.AlmacenId,
                        Almacen = new
                        {
                            x.Almacen?.Codigo,
                            x.Almacen?.Nombre,
                            x.Almacen?.Tipo
                        },
                        Material = new
                        {
                            x.Material?.Codigo,
                            x.Material?.Nombre,
                            UnidadMedida = new
                            {
                                x.Material?.UnidadMedida?.Codigo
                            }
                        },
                        x.Cantidad,
                        x.Precio,
                        x.PrecioTotal,
                        x.Periodo
                    })
                });
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

    }
}

SISALM.WebApp/Controllers/PersonaController.cs
using Microsoft.AspNetCore.Mvc;
using SISALM.WebApp.Models;

namespace SISALM.WebApp.Controllers
{
    public class PersonaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
          public IActionResult Index02()
        {
            return Ok(new
            {
                mensaje="new"
            });
        }

        public IActionResult Nuevo()
        {
            string mensaje = "Prospecto";
            ViewBag.Mensaje = mensaje;

            PersonaModel model = new() 
            {
              Nombre = "Junior",
                //Apellido = "Sulca",
                Activo = true,
                Nacimiento = DateTime.Today
            };
            return View(model);
        }

    }
}

SISALM.WebApp/Views/Shared/_Error.cshtml
<div class="alert alert-danger alert-dismissible text-sm mb-0 pb-0">
    <h6><i class="icon fa fa-ban"></i> Error!</h6>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    @if (!ViewData.ModelState.IsValid)
    {
        <strong>Resuelva las siguientes inconsistencias</strong>
        <div asp-validation-summary="All"></div>
    }
    else if (ViewBag.Message != null)
    {
        <label class="mb-3">@ViewBag.Message</label>
    }
    else
    {
        <label class="mb-3">Algo salió mal y no estamos seguros qué, por favor inténtelo más tarde o contácte al administrador del sistema.</label>
    }
</div>

SISALM.WebApp/Views/Shared/_Footer.cshtml
<div class="fixed-bottom bg-light">
    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <i class="fa-brands fa-youtube"></i>
                </a>
                <span class="mb-3 mb-md-0 text-muted">© @DateTime.Today.Year - Junior Sulca</span>
            </div>
            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-twitter"></i></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-instagram"></i></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-facebook"></i></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-telegram"></i></a></li>
            </ul>
        </footer>
    </div>
</div>

SISALM.WebApp/Views/Shared/_Header.cshtml
@{
    string url = Context.Request.Path.ToUriComponent();
    if (url == "/") url = "/Home";
}
<header>
    <div class="px-3 py-2 text-bg-dark">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                    <h3><i class="fa-brands fa-github me-2"></i></h3>
                </a>
                <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small text-center">
                    <li>
                        <a class="nav-link @MenuActivo(url, "/Home")" asp-controller="Home" asp-action="Index" asp-area="">
                            <i class="fa fa-home d-block mx-auto mb-1"></i>
                            Home
                        </a>
                    </li>
                    <li>
                        <a class="nav-link @MenuActivo(url, "/Dashboard")" asp-controller="Dashboard" asp-action="Index" asp-area="">
                            <i class="fa-solid fa-chart-simple d-block mx-auto mb-1"></i>
                            Dashboard
                        </a>
                    </li>
                    <li>
                        <a class="nav-link @MenuActivo(url, "/General")" asp-controller="MetaDato" asp-action="Index" asp-area="General">
                            <i class="fa fa-cloud d-block mx-auto mb-1"></i>
                            General
                        </a>
                    </li>
                    <li>
                        <a class="nav-link @MenuActivo(url, "/Logistica")" asp-controller="AlmacenMaterial" asp-action="Index" asp-area="Logistica">
                            <i class="fa-solid fa-cart-flatbed d-block mx-auto mb-1"></i>
                            Logistica
                        </a>
                    </li>
                    <li>
                        <a class="nav-link @MenuActivo(url, "/Persona")" asp-controller="Persona" asp-action="Index02" asp-area="">
                            <i class="fa-solid fa-user d-block mx-auto mb-1"></i>
                            Persona
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    @await Html.PartialAsync("~/Views/Shared/_SubHeader.cshtml")
</header>
@functions {
    string MenuActivo(string url, string ruta)
    {
        string respuesta = "text-white";
        if (url.Contains(ruta)) respuesta = "text-secondary";
        return respuesta;
    }
}

SISALM.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-pe">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - SISALM</title><!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body class="bg-light">
    @await Html.PartialAsync("~/Views/Shared/_Header.cshtml")
    <div class="container">
        <main role="main" class="pb-3 mt-3">
            @RenderBody()
        </main>
    </div>
    @await Html.PartialAsync("~/Views/Shared/_Footer.cshtml")

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/enumerables.js" asp-append-version="true"></script>
    <script src="~/js/sweetalert2.config.js"></script>
    @await RenderSectionAsync("scripts", required: false)
</body>
</html>

SISALM.WebApp/Views/Shared/_SubHeader.cshtml
@{
    Modulo? modulo = ViewBag.Modulo;
    string url = Context.Request.Path.ToUriComponent();

    const string GENERAL_MATERIAL = "/General/Material";
    const string GENERAL_METADATO = "/General/MetaDato";
    const string GENERAL_ALMACEN = "/General/Almacen";

    const string LOGISTICA_NOTAENTRADA = "/Logistica/NotaEntrada";
    const string LOGISTICA_NOTASALIDA = "/Logistica/NotaSalida";
    const string LOGISTICA_ALMACENMATERIAL = "/Logistica/AlmacenMaterial";
    const string LOGISTICA_MOVIMIENTO = "/Logistica/Movimiento";
}

@if (modulo.HasValue)
{
    <header class="d-flex justify-content-center py-1 bg-white">
        <ul class="nav nav-pills">
            @switch (modulo)
            {
                case Modulo.DASHBOARD:
                    <li class="nav-item"><a href="#" class="nav-link">General</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">Valorizacion</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">Stocks</a></li>
                    break;

                case Modulo.GENERAL:
                    <li class="nav-item"><a href="@GENERAL_MATERIAL" class="nav-link @PaginaActiva(url, GENERAL_MATERIAL)">Material</a></li>
                    <li class="nav-item"><a href="@GENERAL_METADATO" class="nav-link @PaginaActiva(url, GENERAL_METADATO)">MetaDato</a></li>
                    <li class="nav-item"><a href="@GENERAL_ALMACEN" class="nav-link @PaginaActiva(url, GENERAL_ALMACEN)">Almacen</a></li>
                    break;

                case Modulo.LOGISTICA:
                    <li class="nav-item"><a href="@LOGISTICA_NOTAENTRADA" class="nav-link @PaginaActiva(url, LOGISTICA_NOTAENTRADA)">Nota Entrada</a></li>
                    <li class="nav-item"><a href="@LOGISTICA_NOTASALIDA" class="nav-link @PaginaActiva(url, LOGISTICA_NOTASALIDA)">Nota de Salida</a></li>
                    <li class="nav-item"><a href="@LOGISTICA_ALMACENMATERIAL" class="nav-link @PaginaActiva(url, LOGISTICA_ALMACENMATERIAL)">Almacen</a></li>
                    <li class="nav-item"><a href="@LOGISTICA_MOVIMIENTO" class="nav-link @PaginaActiva(url, LOGISTICA_MOVIMIENTO)">Kardex</a></li>
                    break;
            }
        </ul>
    </header>
}

@functions 
{
    string? PaginaActiva(string url, string ruta)
    {
        string? respuesta = null;
        if (url.Contains(ruta)) respuesta = "active";
        return respuesta;
    }
}